name = "color"
type = "webpack"
account_id = "998c66447b7b4c67497c499a9ab1b7dd"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./out"
entry-point = "workers-site"

[env.production]
# The ID of the domain to deploying to
zone_id = "e878d49a02187283ffcfa2e254f04540"

# The route pattern your Workers application will be served at
route = "color.cloudflare.design/*"